#https://pspdfkit.com/blog/2018/how-to-use-docker-compose-to-run-multiple-instances-of-a-service-in-development/
#https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-multi-container-app
#https://blog.lukasvavrek.com/containers-on-microsoft-azure/

#cd web-api
#gox -osarch="linux/amd64" --output="build/app"
#cd..
#docker-compose up --scale go-web-api=4
#docker-compose down

version: '3'
services: 
  go-web-api:
    build: ./web-api
    image: "digitalconsulting.azurecr.io/go-web-api"
    ports: 
      - "4040"
  go-front-end:
    build: ./nginx
    image: "digitalconsulting.azurecr.io/go-front-end"
    ports:
      - "4000:4000"
    depends_on: 
      - "go-web-api"
    